# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build api`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t api`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

# Install OpenSSL
RUN apk add --no-cache openssl

RUN addgroup --system api && \
    adduser --system -G api api

# Copy package files and prisma files
COPY package*.json ./
COPY src/prisma ./prisma/

# Create prisma directory if it doesn't exist
RUN mkdir -p prisma

# Install dependencies including devDependencies (needed for prisma generate)
RUN npm install

# Generate Prisma Client
RUN cd prisma && npx prisma generate

# Copy the rest of the application
COPY dist/api api
RUN chown -R api:api .

# Install production dependencies only
RUN npm --prefix api --omit=dev -f install

# Switch to non-root user
USER api

CMD [ "node", "api" ]
