# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build api`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t api`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

# Install OpenSSL
RUN apk add --no-cache openssl

RUN addgroup --system api && \
    adduser --system -G api api

# Copy package files and prisma files
COPY package*.json ./
COPY src/prisma ./prisma/

# Create prisma directory if it doesn't exist
RUN mkdir -p prisma

# Install dependencies including devDependencies (needed for prisma generate)
RUN npm install

# Copy the application first
COPY dist/api api

# Update package.json in api directory and generate Prisma Client
RUN cd api && \
    cp -r ../prisma . && \
    npm install @prisma/client && \
    # Update prisma schema path in package.json
    sed -i 's|"schema": "src/prisma/schema.prisma"|"schema": "prisma/schema.prisma"|g' package.json && \
    sed -i 's|"seed": "src/prisma/seed.ts"|"seed": "prisma/seed.ts"|g' package.json && \
    npx prisma generate && \
    cd ..

# Set proper ownership
RUN chown -R api:api .

# Install production dependencies only
RUN npm --prefix api --omit=dev -f install

# Switch to non-root user
USER api

# Set working directory to api
WORKDIR /app/api

# Use main.js as the entry point
CMD [ "node", "main.js" ]
